name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Jekyll Actions
    uses: helaili/jekyll-action@2.0.3
    with:
      # The Jekyll website source directory
      jekyll_src: # optional
